### PR TITLE
Q070 and some macro refactoring

### PR DESCRIPTION
**Pull request by porterbot**
cfpb/hmda-pilot#139

### CODE REVIEW

**Comment by stevejameskent** [comment]
@porterbot The queries are still a little bit messed up in this. They should be 
total: 
```JSON
{
    "activity_year": activityYear, 
    "respondent_id": respondentID,
    "loan_purpose": {$in: ["1", "3"]},
    "action_type": {$in: ["1", "6"]},
    "property_type": {$in: ["1", "2"]}
}
```
fannie / freddie: 
```JSON
{
    "activity_year": activityYear, 
    "respondent_id": respondentID,
    "loan_purpose": {$in: ["1", "3"]},
    "action_type": {$in: ["1", "6"]},
    "property_type": {$in: ["1", "2"]},
    "purchaser_type": {$in: ["1", "3"]}
}
```
Also, do we need to include a such a large data file? It would probably be better for the unit tests to generate a test set similar to what exists in testdata.js:
```JavaScript
var lars = [],
    sampleLar = {
      'activity_year': '2012',
      'respondent_id': '0201590731',
      'agency_code': '9',
      'loan_type': '1',
      'loan_purpose': '1',
      'loan_amount': '00110',
      'action_type': '1',
      'purchaser_type': '2',
      'property_type': '2'
    };

for (var i = 0; i < 1000; i++) {
  lars.push(sampleLar);
}
mongoose.model('Lar').create(lars, function(err, item) {});
```

**Comment by stevejameskent** [comment]
@porterbot for the test data, I'm referring to this ~77k line json file (data/lar.json) not the smaller chunk. The smaller one can stay the way it was before if that's clearer. In other tests that use more than a few dozen lars I generated test data in a for loop to cut back on file size and control the exact number of entries in order to test edge conditions. For example, generating 1000 lars for isValidNumLoans so that we can test what happens for exactly a +/- 20% difference.

**Comment by LinuxBozo** [comment]
`data/lar.json` is not test data. It's the actual data the gets populated in mongo. Not sure why it was changed at this point.

**Comment by stevejameskent** [comment]
Well that was silly of me, I guess I saw it added in a commit and assumed it must be new test data. 

@porterbot ignore my derpy brainfart I guess. It all looks fine otherwise.

**Pull request merged**
