### PR TITLE
Docker setup for mongodb and api

### PR DESCRIPTION
**Pull request by LinuxBozo**
@jmarin Figured you'd want to give this a once over before merge. Looking forward to your comments. I've based this on `develop` branch, so once this is merged there, it will need another merge over to `master` at some point.

A couple of notes:
 - MongoDB package on Alpine is part of the `testing` repo, and is not ready to go. It bombs when installed. Since Alpine uses musl-libc, not glibc, this causes a problem when compiling or using the binary distribution of Mongo as well. However, I've found a workaround to use the MongoDB distributed binary, as you can see in comments in `mongo-docker/run.sh` build script.
 - As defined, the mongodb image with Alpine comes in at around 138 MB, official mongo image, which is debian wheezy, sits at 261 MB. So definitely worth the headaches of the workaround.
 - The API container runs node directly, and should probably be linked together with a nginx container in front for performance. I might add support for this in the UI docker, since I'll have to run nginx there anyway to serve up the UI bits since they are static. Will just use a proxy like setup in nginx.

Hopefully I've commented enough that things are easy to follow.

### CODE REVIEW

**Comment by jmarin** [comment]
@LinuxBozo Overall this looks good, just a couple of minor comments:

1. Travis seems to have been unhappy with this change and has a failed check. Not sure if that was just a glitch

2. I'd like the environment variables to change to something like the following, to better follow our setup for other containers:

HMDA_PILOT_MONGODB_HOST
HMDA_PILOT_MONGODB_PORT

**Comment by LinuxBozo** [comment]
@jmarin 
1. Yeah, it appears that Travis has changed some things since the last time we've run jobs. I'll dig into that and see what's up. It seems to be complaining about running on old infrastructure and not the new containerized version.
2. The environment variables used follow the naming guidelines set by Docker, which is 
`<image tag>_PORT_<exposed port>_TCP_ADDR` and 
`<image tag>_PORT_<exposed port>_TCP_PORT` . 
These are set automatically when you use `--link` to link containers with exposed ports together, so you don't have to define any env vars yourself. Are you sure you want to break this known convention? Or do you mean you want additional functionality to support both naming schemes?

**Comment by jmarin** [comment]
@LinuxBozo Regarding environment variables, we don't use the Docker convention for using `--link` as that is assumed to work in the same host (as of this writing at least) and we will potentially run these in different machines. Additional functionality to also understand the format that I proposed would be great

**Comment by LinuxBozo** [comment]
@jmarin Ok, this should be good to go now..

**Comment by jmarin** [comment]
@LinuxBozo When running `build-docker-containers.sh` I get the following error in the hmda-pilot-api container (fresh clone of the repo, building from your docker branch):

`it should install nodejs 0.12.5... fail`

**Comment by LinuxBozo** [comment]
@jmarin do you see a failure in the compilation step for node somewhere? I had @doelleri run as well to double check myself, and he didn't see this, so wondering if there is any other output to help solve this for you..

**Comment by jmarin** [comment]
@LinuxBozo Some progress. I cleared all my docker images and am able to build and run the containers. The problem now is that I get a 403 Forbidden when hitting the URL of the hmda-pilot container. I just built and run all 3 containers with the provided scripts. Am I missing something?

**Comment by LinuxBozo** [comment]
@jmarin I'm betting you ran into the same thing that @doelleri did. Make sure that you have nodejs/grunt installed locally for building the hmda-pilot container.. it requires that `grunt` run the build task to generate the `dist` folder of the static site setup for running within the docker container.. While the API container doesn't have any local requirements during build, since node is built in the container itself, the pilot container requires it locally during the build..

**Pull request merged**
